config/routes.rb
Rails.application.routes.draw do

  resources :admins
  resources :admin_watchdogs
  resources :users
  
  resources :passwords,
    controller: 'clearance/passwords',
    only: [:create, :new]

  resource :session,
    controller: 'clearance/sessions',
    only: [:create]

  resources :admins,
    controller: 'clearance/admins',
    only: Clearance.configuration.user_actions do
      resource :password,
        controller: 'clearance/passwords',
        only: [:create, :edit, :update]
    end

  get '/sign_in' => 'clearance/sessions#new', as: 'sign_in'
  delete '/sign_out' => 'clearance/sessions#destroy', as: 'sign_out'

  if Clearance.configuration.allow_sign_up?
    get '/sign_up' => 'clearance/admins#new', as: 'sign_up'
  end

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "admins#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
    include Clearance::User
end

app/models/admin_watchdog.rb
class AdminWatchdog < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

end

app/controllers/admin_watchdogs_controller.rb
class AdminWatchdogsController < ApplicationController
  before_action :set_admin_watchdog, only: [:show, :edit, :update, :destroy]

  # GET /admin_watchdogs
  # GET /admin_watchdogs.json
  def index
    @admin_watchdogs = AdminWatchdog.all
  end

  # GET /admin_watchdogs/1
  # GET /admin_watchdogs/1.json
  def show
  end

  # GET /admin_watchdogs/new
  def new
    @admin_watchdog = AdminWatchdog.new
  end

  # GET /admin_watchdogs/1/edit
  def edit
  end

  # POST /admin_watchdogs
  # POST /admin_watchdogs.json
  def create
    @admin_watchdog = AdminWatchdog.new(admin_watchdog_params)

    respond_to do |format|
      if @admin_watchdog.save
        format.html { redirect_to @admin_watchdog, notice: 'Admin watchdog was successfully created.' }
        format.json { render :show, status: :created, location: @admin_watchdog }
      else
        format.html { render :new }
        format.json { render json: @admin_watchdog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin_watchdogs/1
  # PATCH/PUT /admin_watchdogs/1.json
  def update
    respond_to do |format|
      if @admin_watchdog.update(admin_watchdog_params)
        format.html { redirect_to @admin_watchdog, notice: 'Admin watchdog was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_watchdog }
      else
        format.html { render :edit }
        format.json { render json: @admin_watchdog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin_watchdogs/1
  # DELETE /admin_watchdogs/1.json
  def destroy
    @admin_watchdog.destroy
    respond_to do |format|
      format.html { redirect_to admin_watchdogs_url, notice: 'Admin watchdog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_watchdog
      @admin_watchdog = AdminWatchdog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_watchdog_params
      params.require(:admin_watchdog).permit(:admin_id, :logintime, :ipaddress, :lastvisit)
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  #before_action :require_login , only: [:show, :edit, :update, :destroy,:index]
  before_action :set_admin, only: [:show, :edit, :update, :destroy]
  #before_action :get_two_factor ,only: [:show, :edit, :update,:index]

  # GET /admins
  # GET /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1
  # GET /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins
  # POST /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        Watchdog.create(:admin_id => @admin.id)
        format.html { redirect_to @admin, notice: 'Admin was successfully created.' }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: 'Admin was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: 'Admin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin
      @admin = Admin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_params
      params.require(:admin).permit(:uuid, :roleid, :username, :firstname, :lastname, :language, :disabled, :loginattempts, :email, :encrypted_password, :confirmation_token, :remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :firstname, :lastname)
    end
end

app/helpers/admin_watchdogs_helper.rb
module AdminWatchdogsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin_watchdogs/_form.html.erb
<%= form_with(model: admin_watchdog, local: true) do |form| %>
  <% if admin_watchdog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_watchdog.errors.count, "error") %> prohibited this admin_watchdog from being saved:</h2>

      <ul>
      <% admin_watchdog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin_id %>
    <%= form.text_area :admin_id %>
  </div>

  <div class="field">
    <%= form.label :logintime %>
    <%= form.datetime_select :logintime %>
  </div>

  <div class="field">
    <%= form.label :ipaddress %>
    <%= form.text_area :ipaddress %>
  </div>

  <div class="field">
    <%= form.label :lastvisit %>
    <%= form.datetime_select :lastvisit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin_watchdogs/edit.html.erb
<h1>Editing Admin Watchdog</h1>

<%= render 'form', admin_watchdog: @admin_watchdog %>

<%= link_to 'Show', @admin_watchdog %> |
<%= link_to 'Back', admin_watchdogs_path %>

app/views/admin_watchdogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Watchdogs</h1>

<table>
  <thead>
    <tr>
      <th>Admin</th>
      <th>Logintime</th>
      <th>Ipaddress</th>
      <th>Lastvisit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_watchdogs.each do |admin_watchdog| %>
      <tr>
        <td><%= admin_watchdog.admin_id %></td>
        <td><%= admin_watchdog.logintime %></td>
        <td><%= admin_watchdog.ipaddress %></td>
        <td><%= admin_watchdog.lastvisit %></td>
        <td><%= link_to 'Show', admin_watchdog %></td>
        <td><%= link_to 'Edit', edit_admin_watchdog_path(admin_watchdog) %></td>
        <td><%= link_to 'Destroy', admin_watchdog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Watchdog', new_admin_watchdog_path %>

app/views/admin_watchdogs/new.html.erb
<h1>New Admin Watchdog</h1>

<%= render 'form', admin_watchdog: @admin_watchdog %>

<%= link_to 'Back', admin_watchdogs_path %>

app/views/admin_watchdogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Admin:</strong>
  <%= @admin_watchdog.admin_id %>
</p>

<p>
  <strong>Logintime:</strong>
  <%= @admin_watchdog.logintime %>
</p>

<p>
  <strong>Ipaddress:</strong>
  <%= @admin_watchdog.ipaddress %>
</p>

<p>
  <strong>Lastvisit:</strong>
  <%= @admin_watchdog.lastvisit %>
</p>

<%= link_to 'Edit', edit_admin_watchdog_path(@admin_watchdog) %> |
<%= link_to 'Back', admin_watchdogs_path %>

app/views/admins/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Uuid</th>
      <th>Roleid</th>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Language</th>
      <th>Disabled</th>
      <th>Loginattempts</th>
      <th>Email</th>
      <th>Encrypted password</th>
      <th>Confirmation token</th>
      <th>Remember token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.uuid %></td>
        <td><%= admin.roleid %></td>
        <td><%= admin.username %></td>
        <td><%= admin.firstname %></td>
        <td><%= admin.lastname %></td>
        <td><%= admin.language %></td>
        <td><%= admin.disabled %></td>
        <td><%= admin.loginattempts %></td>
        <td><%= admin.email %></td>
        <td><%= admin.encrypted_password %></td>
        <td><%= admin.confirmation_token %></td>
        <td><%= admin.remember_token %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin', new_admin_path %>

app/views/admins/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @admin do |form| %>
    <%= render partial: '/admins/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uuid:</strong>
  <%= @admin.uuid %>
</p>

<p>
  <strong>Roleid:</strong>
  <%= @admin.roleid %>
</p>

<p>
  <strong>Username:</strong>
  <%= @admin.username %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @admin.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @admin.lastname %>
</p>

<p>
  <strong>Language:</strong>
  <%= @admin.language %>
</p>

<p>
  <strong>Disabled:</strong>
  <%= @admin.disabled %>
</p>

<p>
  <strong>Loginattempts:</strong>
  <%= @admin.loginattempts %>
</p>

<p>
  <strong>Email:</strong>
  <%= @admin.email %>
</p>

<p>
  <strong>Encrypted password:</strong>
  <%= @admin.encrypted_password %>
</p>

<p>
  <strong>Confirmation token:</strong>
  <%= @admin.confirmation_token %>
</p>

<p>
  <strong>Remember token:</strong>
  <%= @admin.remember_token %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
    <% else -%>
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>

  <%= yield %>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Firstname</th>
      <th>Lastname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>